#!/bin/bash

#===============================================================================
#
#          FILE:  ---
#
#         USAGE:  ---
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  ---
#       COMPANY:  ---
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================
{
  #$1 FONTE
  #$2 SORVEDOURO
  #$3 ARQUIVO

  infile=$3

  alfaList=($(awk NR==1 "$infile"))
  awk NR==2 "$infile" > network.in
  awk NR==3 "$infile" >> network.in
  awk "NR>3" "$infile" > auxFile.in

  while read line
  do
    cpt=-1
    lengthLine=$(echo "$line" | awk '{n=split($0, array, " ")} END{print n }')
    firstAlfa=$(echo "$line" | awk '{print $3}')
    if [[ $lengthLine -eq 3 ]]
    then
      if [[ $firstAlfa -gt 0 ]]
      then
        cpt=$(awk "BEGIN {print ${alfaList[0]} * ${alfaList[$firstAlfa]}}")
      else
        cpt=$(awk "BEGIN {print ${alfaList[0]} * (1 - ${alfaList[($firstAlfa * -1)]})}")
      fi
    elif [[ $lengthLine -eq 4 ]]
    then
      secondAlfa=$(echo "$line" | awk '{print $4}')
      if [[ $firstAlfa -gt 0 ]]
      then
        cpt=$(awk "BEGIN {print ${alfaList[0]} * (1 + ${alfaList[$firstAlfa]} - ${alfaList[$secondAlfa]})}")
      else
        cpt=$(awk "BEGIN {print ${alfaList[0]} * (1 - ${alfaList[($firstAlfa * -1)]} - ${alfaList[$secondAlfa]})}")
      fi
    else
      secondAlfa=$(echo "$line" | awk '{print $4}')
      thirdAlfa=$(echo "$line" | awk '{print $5}')
      if [[ $firstAlfa -gt 0 ]]
      then
        cpt=$(awk "BEGIN {print ${alfaList[0]} * ${alfaList[$firstAlfa]} * (1 + ${alfaList[$secondAlfa]} - ${alfaList[$thirdAlfa]})}")
      else
        cpt=$(awk "BEGIN {print ${alfaList[0]} * (1 - ${alfaList[($firstAlfa * -1)]}) * (1 + ${alfaList[$secondAlfa]} - ${alfaList[$thirdAlfa]})}")
      fi
    fi
    n1=$(echo "$line" | awk '{print $1}')
	  n2=$(echo "$line" | awk '{print $2}')
    echo $n1 $n2 $cpt >> network.in
  done < "auxFile.in"
  rm -rf aux*
 ./Ford_Fulkerson < network.in > networkFlow.dat
}
