#!/bin/bash
#===============================================================================
#
#          FILE:  ---
#
#         USAGE:  ---
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  ---
#       COMPANY:  ---
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================
#
{
    cp base-file.in base-aux.in
    # $1 > $2
    j=35
    for (( i=$1; i >= $2; i--))
    do
	sed -i "s/1 3 $j/1 3 $i/" base-aux.in
	./Ford_Fulkerson < base-aux.in > teste"$i".dat
	j=$i
    done
    rm -rf base-aux.in
}
