#!/bin/bash
#===============================================================================
#
#          FILE:  ---
#
#         USAGE:  ---
#
#   DESCRIPTION:
#
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  ---
#       COMPANY:  ---
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  Alexandre 12/6/19
#===============================================================================
#
{
    cp base-file.in base-aux.in
    # argumentos 1 e 2 do script são os nós de inicio e fim de uma dada aresta
    # $1 > $2
    # usar sed para verificar se as arestas usadas como argumento possuem fluxo inicial nao nulo.
    # usar o sed para copiar o valor do fluxo maximo atual da aresta
    # atribuir esse valor a variavel total
    total=35
    j=$total
    # no loop, i varia de $total até 1

    for (( i=$1; i >= $2; i--))
    do
	pct=($( awk "BEGIN { print ($i / $total) * 100 }"))
	sed -i "s/1 3 $j/1 3 $i/" base-aux.in
	./Ford_Fulkerson < base-aux.in > temp"$i".dat
	flw=($(sed -n 's/^total flow is//p' temp"$i".dat))
	echo $pct $flw >> "$1_$2.dat"
	j=$i
    done
    # 1. deletar a linha referente a aresta analisada -> equivale a fluxo nulo na aresta para o programa gerando o novo arquivo base-aux.in 
    # 2. rodar o FF
    # 3. gerar flw
    # 4. adendar os valores $pct #flw no arquivo $1_$2.dat
    rm -rf base-aux.in temp*.dat
}
